name: pricetracker
description: A Price Tracker Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-31.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.2.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_bold.ttf
          weight: 700
        - asset: assets/fonts/lato_regular.ttf
          weight: 400
        - asset: assets/fonts/lato_light.ttf
          weight: 300

